license="MIT"
[[mods]]
modId="shelf_numbers"
version="0.0.5"
displayName="Shelf Numbers"
logoFile="assets/shelf_numbers/icon.png"
authors="Illusioner2520"
description='''
Displays the number of items on shelves
'''

[[mixins]]
config="shelf_numbers.client.mixins.json"

[[dependencies.shelf_numbers]]
    modId="neoforge"
    type="required"
    versionRange="[26.2.0.1-beta,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[26.2,)"
    ordering="NONE"
    side="CLIENT"